### ISSUE TITLE
structsearch problem

### ISSUE THREAD

**Issue by artikandms** [pharmpy/pharmr#161]
Hi again, 
I don't seem to know how to make run_structsearch work. I looked on https://pharmpy.github.io/latest/drug_metabolite.html , and I don't see where my code is wrong. here is my code and my erorr message. my start model is a model with first order absorption and elimination and no peripheral compartment. 
(I am an pharmacometrics intern, so I learn to use the package)
Thanks again

```
 res <- run_structsearch(type='drug_metabolite',
                        search_space='METABOLITE([BASIC,PSC]);PERIPHERALS(0..1,MET)',
                        model=startmodel,
                        results=modelfitresults)
```

<img width="507" alt="Capture d’écran 2024-04-11 153515" src="https://github.com/pharmpy/pharmr/assets/166139814/aa5e20b1-b5af-49dc-901a-8c6c3f312149">

**Comment by artikandms** [comment]
Sorry for the delay. I'm on the 0.108.0 version. My input model is not a drug metabolite model, and my dataset does not contain a DVID column. Is that a problem?

**Comment by artikandms** [comment]
I tried with a drug metabolite model and an appropriate dataset and I now have the message error "Cannot find a central compartment"

**Comment by JohanWBorg** [comment]
Hi!
Yes, your dataset is required to have a DVID column to run drug metabolite, otherwise, the two DVs cannot be separated from one another. However, the input model itself does not need to be a drug metabolite model, a regular PK model is fine.

I can't seem to recreate the issue on my end. Would it be possible to share the model code or give some more information about how it looks? Or for instance, did you load a NONMEM model or create it from scratch within pharmpy?

**Comment by artikandms** [comment]
I loaded a NONMEM model. So I must have a dataset where I have necessarily DVID = 1 and DVID = 2 ? Here are some parts of my model. My reasoning is as follows : maybe pharmr does not recognize V3 and the name of my compartments

```
$MODEL  NCOMP=3
COMP=(DepotOral) 
COMP=(CentralOral) 
COMP=(CentralMetabo)

$PK

  TVV2 = THETA(1)
  TVKA = THETA(2)
  TVCL =  THETA(3)
  TVKM = THETA(4)
  TVKEM = THETA(5)

ETAV2 = ETA(1) 
ETAKA = ETA(2) 
ETACL = ETA(3) 
ETKM = ETA(4)
ETKEM =ETA(5)

V3 = 1

V2 = TVV2 * EXP(ETAV2) 
CL = TVCL * EXP(ETACL)
KA = TVKA * EXP(ETAKA)

KM=TVKM * EXP(ETKM)

KEM = TVKEM * EXP(ETKEM)

$DES
C2=A(2)/V2
C3=A(3)/V3

; CMT Depot
DADT(1) = - KA*A(1)

; central parent oral
DADT(2) =   KA*A(1) - K*A(2)  - KM*A(2)

;CentralMetabo
 DADT(3) =  KM*A(2) - KEM*A(3) 

```

**Comment by JohanWBorg** [comment]
Thank you so much! That's very helpful! I'm looking into the issue.

Yes, currently the two DVIDs 1 and 2 are required where 1 relates to the parent and 2 relates to the metabolite.

You are correct and it seems to be an issue with the parsing of the model, specifically the ODE system. I'll see if I can find a solution for it

**Comment by artikandms** [comment]
Thank you !

Also, I was wondering : 
- With a metabolite model, I can only use the part "PERIPHERALS(0..1,MET)" (because when I try to add "METABOLITE([BASIC;PSC]), pharmR returns that it's not possible yet to do that)

- But with a regular basic pk model, I also need to have a dataset with DVID = 1 and DVID = 2? That makes no sense for me, because if I have this dataset, I already know that I need to have a metabolite model. Can you explain how the function works so I can finally succeed and close this conversation? Many thanks in advance.

**Comment by JohanWBorg** [comment]
What ADVAN are you using for this model, through some of my own testing (with ADVAN 15 for instance) the model was parsed correctly.

To answer your questions

- Yes, that is the case since we do not yet fully support transformations between different types of drug metabolite models. So for instance, we do not support  the transformation of PSC -> BASIC just yet. For this reason, you cannot have a drug metabolite model as an input while also having METABOLITE transformations
- This is due to the fact the pharmr will add the metabolite compartment itself within the tool. The inputted PK model can be seen as a scaled down version of the drug metabolite model where the metabolite compartment has been removed. The tool then adds a metabolite compartment, which is why both DVID 1 and 2 are needed in the dataset. This goes hand in hand with the previous point. Another option would be to run the AMD tool for drug_metabolite modeltype and input only your dataset. It would also try to find the best drug_metabolite model, given your searchspace.

I want to mention that the parsing and support of all kinds of drug metabolite models is still in development. So inputting a custom drug metabolite model to the structsearch tool might not necessarily work in this stage. Currently, inputting a PK model with a dataset with DVID 1 and 2 is preferred.

**Comment by JohanWBorg** [comment]
Hello again!
Did my previous explanation answer your question? If so, please let me know and we will close this issue

**Comment by artikandms** [comment]
Yes ! Thank you. It was indeed very useful.
