### ISSUE TITLE
Results reported from a failed run (run_modelsearch)

### ISSUE THREAD

**Issue by schaedeli** [pharmpy/pharmr#71]
I just found this accidentally: the results from a run_modelsearch() step in R listed the OFV and parameter estimates from a run that had failed without reporting a minimization statement and results in the .lst file.

OFV and parameter estimates appear to be retrieved from .ext file and listed as results. Such results should not be used to rank a model, or need to discuss how to rank or flag. Rather, there should be a way or option to retry such failed runs with different initial estimates, as discussed for the starting model. This may need to be further discussed.

Kind Regards
Franziska
![Capture](https://user-images.githubusercontent.com/106077991/171144703-bb2284d1-ba3a-459f-ae21-9a627cb9180c.PNG)

**Comment by joaoabr** [comment]
**Example 1**
#TERM:
0MINIMIZATION TERMINATED
DUE TO ROUNDING ERRORS (ERROR=134)
NO. OF FUNCTION EVALUATIONS USED:     2320
NO. OF SIG. DIGITS UNREPORTABLE
 

**Example 2** 
#TERM:
0MINIMIZATION TERMINATED
DUE TO PROXIMITY OF LAST ITERATION EST. TO A   VALUE
AT   WHICH THE OBJ. FUNC. IS INFINITE (ERROR=136)
0AT THE LAST COMPUTED INFINITE VALUE OF   THE OBJ. FUNCT.:
ERROR IN NCONTR WITH INDIVIDUAL       4     ID= 3.00000000000000E+01
NUMERICAL HESSIAN OF OBJ. FUNC. FOR   COMPUTING CONDITIONAL ESTIMATE
IS   NON POSITIVE DEFINITE
THETA=
1.15E-01   4.00E-02   1.51E-01     3.34E+04   7.36E-04   5.04E-02     2.94E-03   3.26E-02
 
NO. OF FUNCTION EVALUATIONS USED:     1989
NO. OF SIG. DIGITS UNREPORTABLE
 
 
 
**Example 3 (internal model 5)**
0ITERATION NO.:   29      OBJECTIVE VALUE:    -1493.24082839244        NO. OF   FUNC. EVALS.:  11
CUMULATIVE NO. OF FUNC. EVALS.:      455
NPARAMETR:    2.8612E+02  9.2300E+00  1.5267E+00    4.5970E-01  2.1143E+00  5.7650E+03    2.0103E+01  6.0370E+02  3.5356E-01    2.1244E-01
8.7611E-01  1.5735E+00    2.7782E-03  1.1536E-01
PARAMETER:    5.2425E-03 -7.9206E-02    2.5820E-01  9.5823E-02  1.9781E-01    2.1766E+00  2.5270E-01   -7.9839E-02  6.7840E-02  1.4069E-01
2.4873E-01  3.3442E-02    1.8824E-01  8.1245E-02
GRADIENT:    -4.1684E+00  9.4970E+00  1.7042E+00    7.3843E+00 -3.3038E+01    1.8115E+01  9.6019E+00   -4.1494E+01 -1.4927E+00  2.8012E+00
-9.0707E+00  2.3353E-02    1.8364E-03  1.1435E+01
0PRED EXIT CODE = 1
0INDIVIDUAL NO.      87     ID= 4.00500000000000E+03     (WITHIN-INDIVIDUAL) DATA REC NO.     2
THETA=
2.86E+02   9.08E+00   1.52E+00     4.60E-01   2.19E+00   5.63E+03     2.01E+01   6.03E+02
ETA=
7.42E-02  -1.11E+00   1.78E+00     3.25E-04
OCCURS DURING SEARCH FOR ETA AT A NONZERO   VALUE OF ETA
KA, K32, OR K42 IS TOO CLOSE TO AN   EIGENVALUE
0PROGRAM TERMINATED BY OBJ
MESSAGE ISSUED FROM ESTIMATION STEP
 
#TERM:
 
TOTAL DATA POINTS NORMALLY DISTRIBUTED   (N):          478
N*LOG(2PI) CONSTANT TO OBJECTIVE   FUNCTION:    878.50523774366707
OBJECTIVE FUNCTION VALUE WITHOUT   CONSTANT:   -1494.0812550157616
OBJECTIVE FUNCTION VALUE WITH CONSTANT:      -615.57601727209453
REPORTED OBJECTIVE FUNCTION DOES NOT CONTAIN   CONSTANT
 
TOTAL EFFECTIVE ETAS (NIND*NETA):                           344
 
#TERE:
Elapsed estimation  time in seconds:   746.69
1THERE ARE ERROR MESSAGES IN FILE   PRDERR
#CPUT: Total CPU Time in Seconds,      527.844
Stop Time:
Thu 05/19/2022
6:51 PM
 
 
**Example 4 (internal model 5)**
0ITERATION NO.:    0      OBJECTIVE VALUE:    -1352.24945970797        NO. OF   FUNC. EVALS.:  11
CUMULATIVE NO. OF FUNC. EVALS.:       11
NPARAMETR:    2.6319E+02  9.2206E+00  2.2796E+00    2.1380E+00  4.8928E+03  1.9826E+01    6.0717E+02  2.5000E-01  2.8667E-01    2.1813E-01
8.5991E-01  5.9848E-01    1.0000E-02  1.2749E-01
PARAMETER:    1.0000E-01  1.0000E-01  1.0000E-01    1.0000E-01  1.0000E-01  1.0000E-01    1.0000E-01  1.0000E-01  1.0000E-01    1.0000E-01
1.0000E-01  1.0000E-01    1.0000E-01  1.0000E-01
GRADIENT:    -1.7022E+00  1.1532E+00  2.7067E+01 -5.1865E+00  2.3694E+00 -8.2346E+01 -1.7125E+01   -1.1809E+02  9.4769E+00 -1.6032E+01
-1.0075E-01 -2.6847E+01   -8.1501E-01  1.6168E+02
0PRED EXIT CODE = 1
0INDIVIDUAL NO.     224     ID= 2.10030000000000E+04     (WITHIN-INDIVIDUAL) DATA REC NO.     2
THETA=
2.56E+02   9.22E+00   2.07E+00     2.13E+00   4.89E+03   1.99E+01     5.77E+02   4.73E-01
ETA=
-1.06E+00    -6.89E-01   3.87E-01  -2.99E-02
OCCURS DURING SEARCH FOR ETA AT A NONZERO   VALUE OF ETA
KA, K32, OR K42 IS TOO CLOSE TO AN   EIGENVALUE
0PROGRAM TERMINATED BY OBJ
MESSAGE ISSUED FROM ESTIMATION STEP
 
#TERM:
 
TOTAL DATA POINTS NORMALLY DISTRIBUTED   (N):         1991
N*LOG(2PI) CONSTANT TO OBJECTIVE   FUNCTION:    3659.2132392210065
OBJECTIVE FUNCTION VALUE WITHOUT   CONSTANT:   -1448.4738069768423
OBJECTIVE FUNCTION VALUE WITH CONSTANT:       2210.7394322441642
REPORTED OBJECTIVE FUNCTION DOES NOT CONTAIN   CONSTANT
 
TOTAL EFFECTIVE ETAS (NIND*NETA):                           892
 
#TERE:
Elapsed estimation  time in seconds:    69.52
1THERE ARE ERROR MESSAGES IN FILE   PRDERR
#CPUT: Total CPU Time in Seconds,       47.391
Stop Time:
Thu 05/19/2022
6:39 PM
 
 
 
**Example 5 (internal model 7)**
0ITERATION NO.:    0      OBJECTIVE VALUE:     8905.59930238489        NO. OF   FUNC. EVALS.:   8
CUMULATIVE NO. OF FUNC. EVALS.:        8
NPARAMETR:    7.5000E+02  6.0000E+00  5.0000E-01    6.0000E+00  3.7500E+01  1.0000E-01    1.0000E-02  1.0000E-01  1.0000E-01    9.0000E-02
 
PARAMETER:    1.0000E-01  1.0000E-01  1.0000E-01    1.0000E-01  1.0000E-01  1.0000E-01    1.0000E-01  1.0000E-01  1.0000E-01    1.0000E-01
 
GRADIENT:     3.5432E+02  2.6316E+02  2.6959E+02    2.9922E+01 -1.3832E+02 -2.3280E+02 -1.3783E+02 -5.2278E+02 -9.9380E+01   -7.2496E+03
 
0PRED EXIT CODE = 1
0INDIVIDUAL NO.      35     ID= 5.20000000000000E+01     (WITHIN-INDIVIDUAL) DATA REC NO.     2
THETA=
7.50E+00   2.32E-01   3.94E+02     3.59E+00   2.31E+03
ETA=
-3.03E+01     2.04E+00  -1.10E+00
OCCURS DURING SEARCH FOR ETA AT A NONZERO   VALUE OF ETA
A   ROOT OF THE CHARACTERISTIC EQUATION IS ZERO BECAUSE
K*K32 IS MUCH SMALLER THAN  (K+K23+K32)**2.
PERHAPS K OR K32 IS VERY SMALL, OR K23 IS   VERY LARGE.
0PROGRAM TERMINATED BY OBJ
MESSAGE ISSUED FROM ESTIMATION STEP
 
#TERM:
 
TOTAL DATA POINTS NORMALLY DISTRIBUTED   (N):          739
N*LOG(2PI) CONSTANT TO OBJECTIVE   FUNCTION:    1358.1911520765061
OBJECTIVE FUNCTION VALUE WITHOUT   CONSTANT:    3168.0038697225455
OBJECTIVE FUNCTION VALUE WITH CONSTANT:       4526.1950217990516
REPORTED OBJECTIVE FUNCTION DOES NOT CONTAIN   CONSTANT
 
TOTAL EFFECTIVE ETAS (NIND*NETA):                           102
 
#TERE:
Elapsed estimation  time in seconds:     3.20
1THERE ARE ERROR MESSAGES IN FILE   PRDERR
#CPUT: Total CPU Time in Seconds,        3.891
Stop Time:
Mon 05/30/2022
12:18 PM
 
 
**Example 6 (internal model 7)**
MONITORING OF SEARCH:
 
0PROGRAM TERMINATED BY OBJ
ERROR IN NCONTR WITH INDIVIDUAL      29     ID= 4.40000000000000E+01
NUMERICAL HESSIAN OF OBJ. FUNC. FOR   COMPUTING CONDITIONAL ESTIMATE
IS   NON POSITIVE DEFINITE
MESSAGE ISSUED FROM ESTIMATION STEP
AT   0TH ITERATION, UPON EVALUATION OF GRADIENT, WITH RESPECT TO OMEGA
0TRY SUBSTANTIALLY INCREASING   "INITIAL ESTIMATE OF SIGMA"
OR   DECREASING "INITIAL ESTIMATE OF OMEGA"
 
#TERM:
 
TOTAL DATA POINTS NORMALLY DISTRIBUTED   (N):          553
N*LOG(2PI) CONSTANT TO OBJECTIVE   FUNCTION:    1016.3460177243679
OBJECTIVE FUNCTION VALUE WITHOUT   CONSTANT:    9013.7315762614871
OBJECTIVE FUNCTION VALUE WITH CONSTANT:       10030.077593985856
REPORTED OBJECTIVE FUNCTION DOES NOT CONTAIN   CONSTANT
 
TOTAL EFFECTIVE ETAS (NIND*NETA):                            84
 
#TERE:
Elapsed estimation  time in seconds:     0.16
#CPUT: Total CPU Time in Seconds,        0.828
Stop Time:
Mon 05/30/2022
11:56 AM
 
 
**Example 7 (internal model 11)**
0ITERATION NO.:  261      OBJECTIVE VALUE:     11547.1762699769        NO. OF   FUNC. EVALS.: 359
CUMULATIVE NO. OF FUNC. EVALS.:     4966
NPARAMETR:    2.1620E+02  4.3306E+00  5.8659E-01    7.4599E-02  8.7774E+00  1.3053E+01    9.9596E+01  5.3496E-01  4.9122E-01    3.0657E-02
1.5398E-01  1.3562E+00    2.4863E+00  4.3965E-02
PARAMETER:    9.9384E-02  9.9440E-02   -4.5356E-01  2.1694E-01  1.7308E-01    3.0168E-01  1.3000E-01   -4.5948E+00  1.2076E-01  1.0522E-01
1.0360E-01 -7.0682E-02  2.8551E+00    9.0417E-02
GRADIENT:     3.8394E+03 -3.8475E+03 -1.6907E+03    1.7701E+03  4.4287E+03   -2.5399E+03  5.8934E+03  0.0000E+00 -6.3477E+03  3.6452E+03
-1.3741E+00  2.6172E+00 -1.3262E+02  7.6632E+03
 
#TERM:
0MINIMIZATION TERMINATED
DUE TO ROUNDING ERRORS (ERROR=134)
NO. OF FUNCTION EVALUATIONS USED:     4966
NO. OF SIG. DIGITS UNREPORTABLE
0PARAMETER ESTIMATE IS NEAR ITS BOUNDARY
 

**Example 8 (internal model 11)**
0ITERATION NO.:   69      OBJECTIVE VALUE:     11571.7498418108        NO. OF   FUNC. EVALS.: 781
CUMULATIVE NO. OF FUNC. EVALS.:     1164
NPARAMETR:    2.1649E+02  4.3390E+00  6.4714E-01    4.4374E-01  1.0767E+01  1.0747E+02    4.7573E-01  3.2939E-02  1.5486E-01    4.7081E-01
3.5248E+00  4.4537E-02
PARAMETER: -3.9204E-01  7.3471E-02    4.8818E+00 -8.6977E-02    9.8208E-01  1.9038E+00  5.1763E-01    5.3863E-02  7.5319E-02  2.0254E+00
2.9347E-01  6.0839E-02
GRADIENT:     2.8554E+03 -5.6136E+03 -1.1538E+02 -1.1213E+04 -5.7514E+02  5.8374E+02 -1.0839E+03  1.1214E+04 -1.1205E-01 -2.7696E+02
-3.8116E+03  5.6102E+03
NUMSIGDIG:         3.3         3.3         3.3         3.3         3.3         3.3         3.3         3.3         2.7         3.3
3.3         3.3
 
#TERM:
0MINIMIZATION TERMINATED
DUE TO ROUNDING ERRORS (ERROR=134)
NO. OF FUNCTION EVALUATIONS USED:     1164
NO. OF SIG. DIGITS IN FINAL EST.:  2.7
